[package]
name = "wltile"
version = "0.3.0"
authors = ["Khaled Eldoheiri <khaled@eldoheiri.com>"]
edition = "2021"
description = "A cli tool that positions outputs/displays for wlroots based compositors"
readme = "README.md"
repository = "https://gitlab.com/eldoheiri/wltile"
license = "GPL-3.0-or-later"
keywords = ["wayland", "wlroots"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
colored = "3.0.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
wayland-client = "0.31.8"
wayland-protocols-wlr = { version = "0.3.6", features = ["client"] }
