[package]
name = "wltile"
description = "A cli tool that positions outputs/displays for wlroot based compositors"
readme = "README.md"
authors = ["Khaled Eldoheiri <khaled@eldoheiri.com>"]
version = "0.1.1-alpha.1"
edition = "2021"
repository = "https://gitlab.com/eldoheiri/wltile"
license = "GPL-2.0-or-later"
keywords = ["wayland", "wlroot"]
categories = ["command-line-utilities"]
publish = false # layer

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
colored = "3.0.0"
log = "0.4.25"
log4rs = "1.3.0"
wayland-client = "0.31.8"
wayland-protocols-wlr = { version = "0.3.6", features = ["client"] }
